package Tests;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.List;
public class ShayYnetNewsTest {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    //driver = new FirefoxDriver();
    System.setProperty("webdriver.chrome.driver","libs/chromedriver.exe");
    driver = new ChromeDriver();
	//DELETE YNET COOCKIE
	driver.manage().deleteCookieNamed("weatherCity");
	//Set<Cookie> allCookies = driver.manage().getCookies();
//for (Cookie cookie : allCookies) {
    //driver.manage().deleteCookieNamed(cookie.getName());
//}
	
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void shayYnetNews() {
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(1020, 720));
    driver.findElement(By.name("q")).click();
    driver.findElement(By.name("q")).sendKeys("ynetnew");
    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    driver.findElement(By.xpath("//span[contains(.,\'https://www.ynetnews.com\')]")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      //wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//img[@alt=\'Ynetnews - news and update 24 hours\']")));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("B14coRYJye3"))); //Main section
    }
    {
      //List<WebElement> elements = driver.findElements(By.xpath("//img[@alt=\'Ynetnews - news and update 24 hours\']"));
      List<WebElement> elements = driver.findElements(By.className("YnetnewsHeader"));
      assert(elements.size() > 0);
    }
    System.out.println( driver.findElement(By.cssSelector(".weathertemps")).getText());
    driver.findElement(By.id("weathercityselect")).click();
    {
      WebElement dropdown = driver.findElement(By.id("weathercityselect"));
      dropdown.findElement(By.xpath("//option[. = 'Eilat']")).click();
    }
    System.out.println( driver.findElement(By.cssSelector(".weathertemps")).getText());
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.xpath("//a/div/span")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(.,\'send to friend\')]"));
      assert(elements.size() > 0);
    }
  }
}
